---
metrics:
  addr: localhost:9090
  endpoint: /metrics
clickhouse:
  dsn: "localhost:8123"
  num_retries: 3
  timeout: 10s # golang time format
  use_tls: false
  user: "default"
  password: "password123"
web_api:
  addr: :8080
